from django.urls import path, re_path

from . import views

urlpatterns = [
    path('assembly/', views.AssemblyView.as_view(), name='assembly'),
    re_path(r'^assembly/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.AssemblyViewDetail.as_view(),
            name='assembly-detail'),
    re_path(r'^assembly/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$', views.AssemblyViewDetailCreateAttrs.as_view(),
            name='assembly-detail-attrs'),
    path('budget/', views.BudgetView.as_view(), name='budget'),
    re_path(r'^budget/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.BudgetViewDetail.as_view(), name='budget-detail'),
    re_path(r'^budget/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$',
            views.OrderByBudgetEntityViewDetailCreateAttrs.as_view(), name='budget-detail-attrs'),
    path('consumable/', views.ConsumableView.as_view(), name='consumable'),
    re_path(r'^consumable/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.ConsumableViewDetail.as_view(),
            name='consumable-detail'),
    re_path(r'^consumable/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$',
            views.ConsumableViewEntityDetailCreateAttrs.as_view(),
            name='consumable-detail-attrs'),
    path('expedition/', views.ExpeditionView.as_view(), name='expedition'),
    re_path(r'^expedition/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$',
            views.ExpeditionViewDetail.as_view(), name='expedition-detail'),
    re_path(r'^expedition/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$',
            views.ExpeditionViewEntityDetailCreateAttrs.as_view(),
            name='expedition-detail-attrs'),

    path('machine/', views.MachineView.as_view(), name='machine'),
    re_path(r'^machine/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.MachineViewDetail.as_view(), name='machine-detail'),
    re_path(r'^machine/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$', views.MachineViewDetailCreateAttrs.as_view(),
            name='machine-detail'),
    path('organization/', views.OrganizationView.as_view(), name='organization'),
    path('organization/<str:pk>/', views.OrganizationViewDetail.as_view(), name='organization-detail'),
    path('owner/', views.OwnerView.as_view(), name='owner'),
    path('owner/<str:pk>/', views.OwnerViewDetail.as_view(), name='owner-detail'),
    path('part/', views.PartView.as_view(), name='part'),
    re_path(r'^part/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.PartViewDetail.as_view(), name='part-detail'),
    re_path(r'^part/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$', views.PartViewDetailCreateAttrs.as_view(),
            name='part-detail-attrs'),
    path('project/', views.ProjectView.as_view(), name='project'),
    path('project/<str:pk>/', views.ProjectViewDetail.as_view(), name='leftover-detail'),
    path('leftover/', views.Leftover.as_view(), name='leftover'),
    re_path(r'^leftover/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.LeftoverDetail.as_view(), name='leftover-detail'),
    re_path(r'^leftover/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$', views.LeftOverEntityDetailCreateAttrs.as_view(),
            name='leftover-detail-attrs'),

    path('worker/', views.WorkerView.as_view(), name='worker'),
    path('worker/<str:pk>/', views.WorkerViewDetail.as_view(), name='worker-detail'),
    path('worker-task/', views.WorkerTaskEntity.as_view(), name='worker-task'),
    re_path(r'^worker-task/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.WorkerTaskEntityDetail.as_view(),
            name='worker-task-detail'),
    re_path(r'^worker-task/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$', views.WorkerTaskEntityDetailCreateAttrs,
            name='worker-task-detail-attrs'),
    # path('machine-task/', views.MachineTaskEntity.as_view(), name='machine-task'),
    # path('machine-task/<str:pk>/', views.MachineTaskEntityDetail.as_view(), name='machine-task-detail'),
    path('furniture/', views.FurnitureView.as_view(), name='furniture'),
    re_path(r'^furniture/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.FurnitureViewDetail.as_view(),
            name='furniture-detail'),
    re_path(r'^furniture/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.FurnitureViewDetailCreateAttrs.as_view(),
            name='furniture-detail-attrs'),
    path('module/', views.ModuleView.as_view(), name='module'),
    re_path(r'^module/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/$', views.ModuleViewDetail.as_view(),
            name='module-detail'),
    re_path(r'^module/(?P<pk>[\w\-:]+:[\w\-:]+:[\w\-:]+)/attrs$', views.ModuleViewDetailCreateAttrs.as_view(),
            name='module-detail-attrs'),
    path('group/', views.GroupView.as_view(), name='group'),
    path('group/<str:pk>/', views.GroupViewDetail.as_view(), name='group-detail'),
    path('check', views.CheckUnique.as_view(), name='check')
]
