# Generated by Django 3.2.18 on 2023-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
    ]
